# Generated by Django 4.2.3 on 2023-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq',
            name='nid',
            field=models.AutoField(db_column='Nid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.AutoField(db_column='Uid', primary_key=True, serialize=False),
        ),
    ]
