# Generated by Django 4.2.3 on 2023-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_eq_nid_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
