# Generated by Django 4.2.3 on 2023-07-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_things_type_alter_users_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
